### PR TITLE
Tests: Migrate from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by mgol**

### CODE REVIEW

**Comment by mgol** [comment]
[The GitHub Actions workflow for this PR](https://github.com/jquery/sizzle/runs/4662743938) run tests on Chrome & Firefox & it succeeded. [A workflow for the same code previously pushed to a branch on the this repo, not my fork](https://github.com/jquery/sizzle/runs/4662685933) successfully run tests on many browsers on BrowserStack. It looks like it works!

**Comment by mgol** [comment]
Since there's just a single job here, we could make it a required one in GitHub settings for this repo easily after this PR is merged.

**Review by timmywil — APPROVED** [review]
LGTM

**Comment by mgol** [comment]
@timmywil I moved `NODE_VERSION` from the `strategy.matrix` to a top-level env variable as otherwise it was influencing the build name and thus I wouldn't be able to set it as a required check without mentioning the Node.js version. I now made it a required check and it seems to be working fine as can be seen on this PR.

**Pull request merged**
