### PR TITLE
Core: Simplify sourceIndex logic for siblingCheck

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by gibson042** [comment]
I'm pretty sure that detached elements can make it to that code, which is why we have the fallback. Did you verify that the unit tests work on both old and new IE? If so, we probably have a coverage gap.

**Comment by stevemao** [comment]
All tests passed on BrowserStack. I manually tested on IE6 and IE7 (will test again just to make sure). Can you elaborate what the logic was for?

**Comment by timmywil** [comment]
@stevemao Sometimes, there was no sourceIndex, so we wanted the precedence to be given to the node that actually had a sourceIndex. Effectively, put disconnected nodes at the end of the list.

**Comment by timmywil** [comment]
I vaguely remember running into that, but maybe we were just being proactive?

**Comment by stevemao** [comment]
If there was no `sourceIndex`, `~b.sourceIndex - ~a.sourceIndex` returns `0` (meaning they don't exist or what?)
I guess when `~b.sourceIndex` is `0` (when `sourceIndex` is `-1`), it fallbacks to `MAX_NEGATIVE`: `~b.sourceIndex || MAX_NEGATIVE`. Not sure why this is necessary.

Anyway, this line of code is not covered by test and there is no comments (and it potentially does a lot of checks). I can't find any docs about `sourceIndex` on mdn (not sure what `sourceIndex = -1` means) :cry: . I believe adding some useful references would be helpful.

Sorry I'm new to the jquery source code and I really wanna help :smiley:

**Comment by stevemao** [comment]
> I guess when ~b.sourceIndex is 0 (when sourceIndex is -1), it fallbacks to MAX_NEGATIVE: ~b.sourceIndex || MAX_NEGATIVE. Not sure why this is necessary.

It looks like if `sourceIndex` is `-1`, it is then the last child (minus meaning counting backwards)? since `0` is the first. It turns `-1` to a maximum number.

**Comment by timmywil** [comment]
@stevemao Ok, sorry, it's been a while since I've looked at this. Not non-existent, equal to -1, which if my memory is right, means the node is disconnected. I think we *do* need the tildes, or the order is reversed, but I'm not sure we need the MAX_NEGATIVE.

**Comment by timmywil** [comment]
By the way, I think I can clear a few things up.

1. This code only runs in browsers that don't have `compareDocumentPosition`, specifically IE6-8, so running tests in anything but those browsers does nothing.
2. It's a microsoft-only property, which is why it doesn't show up on mdn. It's not part of any official spec. The docs for it are on [msdn](https://msdn.microsoft.com/en-us/library/ms534635(v=vs.85).aspx).

**Comment by timmywil** [comment]
Ok, I can at least confirm that the sourceIndex for a disconnected element is -1.

**Comment by stevemao** [comment]
So we assume a disconnected element is the last child? `~b.sourceIndex || MAX_NEGATIVE`

**Comment by timmywil** [comment]
> So we assume a disconnected element is the last child?

I wouldn't phrase it that way. We decided to put disconnected elements at the end of the list when sorting.

**Comment by timmywil** [comment]
At one point, I believe we had this...

```js
b.sourceIndex - a.sourceIndex
```

Notice `b` is before `a`. However, we ran into **some problem that I can't remember** with disconnected elements. Maybe @gibson042 will come back with more info.

**Comment by stevemao** [comment]
Thanks @timmywil , I think it makes sense now. I would like to add a comment here instead. Ideally it would be great if there was a test. Its not very straight forward here and browsers might not have `compareDocumentPosition` or `sourceIndex` so they run through very different code. But we expect the same results.

I don't know how `compareDocumentPosition` handles disconnected elements

**Comment by stevemao** [comment]
> At one point, I believe we had this...
b.sourceIndex - a.sourceIndex

I believe you mean `a.sourceIndex - b.sourceIndex;`

**Comment by timmywil** [comment]
@stevemao I'm surprised you didn't run into test failures in old IE. We do have some sorting tests and your code should have failed because it reverses the order. Are you sure you built Sizzle before running the tests? The tests load `dist/sizzle.js`, not `src/sizzle.js`.

**Comment by stevemao** [comment]
Yes, I can confirm that. 
I don't think there is any tests for disconnected element
It's doesn't reverse the order. 

`~b.sourceIndex - ~a.sourceIndex`
=> `-(b.sourceIndex + 1)` - (-(a.sourceIndex + 1))
=> `a.sourceIndex - b.sourceIndex`

**Comment by timmywil** [comment]
> `~b.sourceIndex - ~a.sourceIndex`

Ah, of course, you switched them. I'm slow today.

**Comment by dmethvin** [comment]
Here's are the related tickets:
http://bugs.jquery.com/ticket/13505
http://bugs.jquery.com/ticket/13331

**Comment by timmywil** [comment]
You're right that we need more sorting tests that include disconnected elements in Sizzle, but we do have them in jQuery.

**Comment by stevemao** [comment]
Thanks guys, I understand it now :smile:

**Comment by timmywil** [comment]
Correcting myself yet again. More sorting tests (with detached nodes) are [here](https://github.com/jquery/sizzle/blob/master/test/unit/utilities.js#L90)

**Comment by timmywil** [comment]
Wow, I found it! https://github.com/jquery/sizzle/commit/1728f0199bd5b7b3b33082487ff9815e3af80e1c

Text nodes don't have sourceIndex. The test for it is in jQuery.

**Comment by timmywil** [comment]
@stevemao Would you be up for adding a comment? We can avoid this rigamarole in the future.

**Comment by mzgol** [comment]
@timmywil Shouldn't a proper test be in the Sizzle repo?

**Comment by stevemao** [comment]
Yes

**Comment by stevemao** [comment]
@timmywil that detached test passed on my ie6 virtual machine...
1728f01 is a different issue.

**Comment by timmywil** [comment]
@stevemao yea, but the MAX_NEGATIVE code is there to address text nodes, not detached elements.

**Comment by timmywil** [comment]
I'm not overly concerned about having the test in Sizzle. It's very edge despite all the conversation we've had here trying to remember where that code came from.

**Comment by stevemao** [comment]
@timmywil How? I though `MAX_NEGATIVE` is to handle `sourceIndex` equals `-1`?

**Comment by stevemao** [comment]
If there they are text nodes don't sort on sourceIndex

**Comment by timmywil** [comment]
> If there they are text nodes don't sort on sourceIndex

@stevemao It's just faster if you use `sourceIndex`. The code may be harder to read, but it's gone through many, many revisions. Given that we're not actually talking about a bug, I'm inclined to leave it the way it is.

**Comment by mzgol** [comment]
> I'm not overly concerned about having the test in Sizzle. It's very edge despite all the conversation we've had here trying to remember where that code came from.

If the test was here, the PR would fail tests and there wouldn't be so much guessing... Why not add a test since the case has already been re-discovered?

**Comment by timmywil** [comment]
> If the test was here, the PR would fail tests and there wouldn't be so much guessing... Why not add a test since the case has already been re-discovered?

Heh, that's a fair point.

**Comment by stevemao** [comment]
Yeah, the code here is correct. I'm saying if any of them is text node, you can't use `sourceIndex`. `MAX_NEGATIVE` is not to address text node but to put `sourceIndex` -1 to the end of the list when sorting

**Comment by timmywil** [comment]
> Yeah, the code here is correct. I'm saying if any of them is text node, you can't use sourceIndex. MAX_NEGATIVE is not to address text node but to put sourceIndex = -1 to the end of the list when sorting

It handles text nodes indirectly in combination with the tilde.

**Comment by stevemao** [comment]
> It handles text nodes indirectly in combination with the tilde.

Hm... care to elaborate more? I'd really appreciate that :)

**Comment by gibson042** [comment]
Actually, given that the elements are guaranteed to be siblings since c0d9badeb5dac649d0ba7824efaebbe4155369b5, this code change is probably fine.  @stevemao, please ensure a test case in test/unit/utilities.js (e.g., resequence [`Detached children`](https://github.com/jquery/sizzle/blob/51f87d087ac68f897c56fe5229f56105b36ba5d0/test/unit/utilities.js#L141) input) and I'll land it. Thanks!

**Comment by stevemao** [comment]
@gibson042 hmm... not sure you want me to do. all existing tests pass from ie6 to latest on my vm.

**Comment by gibson042** [comment]
I want you to make the tests _better_ by showing that uniqueSort unjumbles detached siblings into DOM order.

**Comment by stevemao** [comment]
Done @gibson042 , let me know what you think. Thanks :)

**Comment by timmywil** [comment]
@gibson042 @stevemao Just to be safe, we should probably run this change through jQuery's traversing tests to be sure we didn't break something.

**Comment by timmywil** [comment]
@gibson042 @stevemao Oh, and forgive me for processing externally so much. I was posting comments while I tried to understand, which usually ends up with me correcting myself a lot. You're right @stevemao. The change I linked to was not the one I was thinking of. With the nodeType checks, we don't use `sourceIndex` for text nodes. I understand now how the MAX_NEGATIVE check started, but we don't use it that way anymore.

**Comment by timmywil** [comment]
I went ahead and ran this change against IE8 in jQuery's compat and 1.12-stable test suites, just to be sure we can include this in 1.12. All good.

**Comment by gibson042** [comment]
Thanks @stevemao!

**Comment by stevemao** [comment]
Thank you for your time guys :) I'll definitely contribute more. It's challenging and fun :)

**Pull request closed without merging**
