### PR TITLE
Fix jquery/jquery#3555 (golfing 21 bytes)

### PR DESCRIPTION
**Pull request by luis140219**
Fixes jquery/jquery#3555.

### CODE REVIEW

**Comment by gibson042** [comment]
@jquery/core This doesn't actually affect the min+gz size of either Sizzle or jQuery. Does it read better to y'all, and if not do you feel like the minor non-gzipped savings justify it? To be honest, I'm ambivalent.
```
   raw     gz Sizes                                                            
 65489  19602 dist/sizzle.js                                                   
 19951   7409 dist/sizzle.min.js                                               

   raw     gz Compared to last run                                             
   -21     -6 dist/sizzle.js                                                   
    -7      = dist/sizzle.min.js
```

```
   raw     gz Sizes                                                            
268324  79525 dist/jquery.js                                                   
 86817  30109 dist/jquery.min.js                                               

   raw     gz Compared to master @ fc34dbc27124a49ba5e3d492de0bfc50fe75ba61    
   -21     -8 dist/jquery.js                                                   
    -7      = dist/jquery.min.js                                               
```

**Comment by markelog** [comment]
-1 if there is no savings

**Comment by mgol** [comment]
Yeah, I assumed these are minified + gzipped differences. If the final size is the same, I think current version reads better so I'd leave it as it is.

**Comment by timmywil** [comment]
Thanks for the PR, but we're going to leave this as-is.

**Pull request closed without merging**
