### PR TITLE
Fix jQuery #13936: iframe reload should not affect Sizzle

### PR DESCRIPTION
**Pull request by markelog**
If iframe document is assigned to "document" variable and if iframe has been reloaded,
IE will throw "permission denied" error when accessing "document" variable.

I see two way of fixing this ticket: or event listener or try...catch statements, i chose the first one.

### CODE REVIEW

**Comment by carolinerioux** [comment]
Is there a plan to fix this for IE11? We see the problem in our app as well. The try-catch approach did solve it for us, but we would like to see it officially patched in jQuery.

The try-catch is referenced here:
http://stackoverflow.com/questions/5352057/script70-permission-denied-ie9

**Comment by gibson042** [comment]
3926b2837d227a52da55b2826594d66826a10b6c should have fixed the issue for IE11. It is already in the master branch, and will be included in the next Sizzle release (and correspondingly, jQuery 3).

**Comment by carolinerioux** [comment]
Thank you!

When is the next sizzle release expected?

Caroline

**Comment by gibson042** [comment]
It should be out by the end of the month, but I don't think a new jQuery is expected until next year.

**Pull request closed without merging**
