### PR TITLE
Fix error js elem.getAttribute is not a function when element is a comment node

### PR DESCRIPTION
**Pull request by kris-2k15**
Fix error js elem.getAttribute is not a function when element is a comment node

### CODE REVIEW

**Comment by gibson042** [comment]
Comment nodes are not valid input... how did you encounter this situation?

**Comment by timmywil** [comment]
Thanks for your willingness to contribute. However, the first step is to open an issue with a test case before opening a PR.

**Comment by kris-2k15** [comment]
Hello, i can't reproduce it in easy test case. no jsfiddle or codepen.
I use angularjs, jquery, foundation.
When i use ng-if and tooltip foundation, an element in dom is changed to comment node by angularjs and i have error js : elem.getAttribute is not a function. This error break in Sizzle.attr 

Thank you

**Comment by timmywil** [comment]
> i can't reproduce it in easy test case. no jsfiddle or codepen.

We can't accept a PR without a test case. It should be possible to reproduce it if you spend more time researching. The [forums](http://forum.jquery.com) and the #jquery and #angularjs irc channels are good places to find help.

**Pull request closed without merging**
