### PR TITLE
Build: update browser launchers

### PR DESCRIPTION
**Pull request by markelog**
* Add Safari 8

* Update Chrome, Firefox and Opera

* Add Yandex.Browser

* Update above browsers to OS X Yosemite

If there is no objections i will merge it tomorrow.

/cc @mzgol

### CODE REVIEW

**Comment by mzgol** [comment]
I guess I can close #289 now, then. ;p

**Comment by mzgol** [comment]
Actually, please re-submit a PR from origin and not your fork as I did in #289 as otherwise we won't know if the changes pass the tests.

I hold off with merging #289 for some time because of issues that wouldn't be catched if I submitted a PR from my own fork.

**Comment by markelog** [comment]
Oh, sorry, @mzgol, i checked the issues list but not the pull one.

> please re-submit a PR from origin

I checked it before submitting, since Sizzle still uses my browserstack credentials i think we are safe here :-).  Or you would need more concrete proof then my word :-)?

**Comment by mzgol** [comment]
> I checked it before submitting, since Sizzle still uses my browserstack credentials i think we are safe here

OK then! :) I was afraid it might fail as it was broken when I was submitting my PR.

Travis *might* be a little different than our local machines but the risk is probably low.

LGTM!

**Pull request closed without merging**
