### PR TITLE
ID with a leading dot should not throw an exception

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
Ref: https://github.com/jquery/sizzle/issues/320

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
I am not sure what happened. I have signed the CLA but the bot is still complaining.

**Comment by arthurvr** [comment]
@FagnerMartinsBrack I just confirmed you signed the CLA. The bot only runs when you push.

**Comment by FagnerMartinsBrack** [comment]
I changed the commit hash earlier and it still didn't run.

**Comment by arthurvr** [comment]
> I changed the commit hash earlier and it still didn't run.

Yeah, I see. That's weird. /cc @scottgonzalez @gnarf

**Comment by gibson042** [comment]
Here's the spec for id selectors: http://www.w3.org/TR/css3-selectors/#id-selectors

"." is not a valid identifier character, so the error is appropriate.

**Pull request closed without merging**
