### PR TITLE
Update my information in AUTHORS.txt

### PR DESCRIPTION
**Pull request by SaptakS**

### CODE REVIEW

**Comment by mgol** [comment]
Please also add correct entries to `.mailmap`. You need to declare the main mail and map others to it; see [these lines](https://github.com/jquery/sizzle/blob/3a3db6ce247c8ff6903b301fa83f2a8018363eb7/.mailmap#L87-L90) as an example.

**Comment by timmywil** [comment]
Also, we update AUTHORS.txt using a grunt task. You should only have to edit the mailmap.

**Comment by SaptakS** [comment]
@mgol my name isn't there in the `.mailmap`. Should I add it at the end?

**Comment by mgol** [comment]
> @mgol <https://github.com/mgol> my name isn't there in the .mailmap.
> Should I add it at the end?
>
Yes. The .mailmap only contains entries that needed corrections; if one
hasn't changed the name or an email then an entry is not needed.


-- 
Michał Gołębiowski

**Comment by SaptakS** [comment]
@mgol made the changes.

**Comment by mgol** [comment]
@timmywil The grunt task only displays the current authors list, it doesn't update anything by itself, does it? The [Release process](https://github.com/jquery/jquery/wiki/Release-process) mentions looking at the output of `grunt authors` & comparing it with the contents of `AUTHORS.txt` which makes for easy misses, especially for older entries.

I'm inclined to accept this PR as is.

**Comment by timmywil** [comment]
@mgol I update AUTHORS.txt with `grunt authors > AUTHORS.txt`, and then remove lines like `Running "authors" task`.

**Comment by SaptakS** [comment]
@timmywil @mgol is there something I am required to do?

**Comment by timmywil** [comment]
Yup, I just checked this. Looks good.

**Comment by SaptakS** [comment]
Thanks.. :+1:

**Pull request closed without merging**
